name: Build and Deploy to Azure k8s

env:
  AZURE_CONTAINER_REGISTRY_NAME: "newregistryACR"
  AZURE_CONTAINER_REGISTRY: "newregistryacr.azurecr.io"
  CONTAINER_NAME: "hello-world"
  RESOURCE_GROUP: "github-cicd-demo"
  CLUSTER_NAME: "aksnewcluster"
  DEPLOYMENT_MANIFEST_PATH: "kubernetes"

# Retrieve below secrets from GitHub Actions Secrets
# AZURE_TENANT_ID: "secrets"
# AZURE_SUBSCRIPTION_ID: "secrets"
# AZURE_CLIENT_ID: "secrets"
# AZURE_CONTAINER_REGISTRY_PASSWORD: "secrets"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/bake-action@v4

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          file: ./Dockerfile

  deploytoAzure:
    runs-on: ubuntu-latest
    environment: Production
    needs: [buildImage]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Kube login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          user-kubelogin: 'true'

      - name: Substitute environment variables in a file
        uses: danielr1996/envsubst-action@1.1
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CONTAINER_REGISTRY_NAME: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
          AZURE_CONTAINER_REGISTRY: ${{ env.AZURE_CONTAINER_REGISTRY }}
        with:
          input: ${{ env.DEPLOYMENT_MANIFEST_PATH }}/hello-world-deployment.yaml
          output: hello-world-deployment.yaml

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            ${{ env.DEPLOYMENT_MANIFEST_PATH }}/hello-world-service.yaml
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}


